name: Run Faculty Scraper

on: workflow_dispatch  # Allows manual triggering via Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo ln -s /usr/bin/chromium-browser /usr/bin/chromium

    - name: Run scraper
      run: python scaper.py

    - name: Commit output
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add faculty_emails_advanced.csv pdf_links_to_extract.csv
        git commit -m "Add scraper output [skip ci]" || echo "No changes to commit"
        git push || echo "No changes to commit"
